external/Infomap: external/infomap_repo/Infomap
	cp $< $@

external/infomap_repo/Infomap:
	$(MAKE) -C external/infomap_repo

# This target needs to be phony so it is run every time because only the other
# makefile can determine that there's nothing to be done.
.PHONY: external/infomap_repo/Infomap
